package gov.nih.nci.cagrid.fqp.resultsretrieval.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.4
 */
public interface FederatedQueryResultsRetrievalConstantsBase {
	public static final String SERVICE_NS = "http://fqp.cagrid.nci.nih.gov/FederatedQueryProcessor/ResultsRetrieval";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "FederatedQueryResultsRetrievalKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "FederatedQueryResultsRetrievalResourceProperties");
	public static final QName FEDERATEDQUERYEXECUTIONSTATUS = new QName("http://fqp.cagrid.nci.nih.gov/FederatedQueryResultsMetadata", "FederatedQueryExecutionStatus");
	public static final QName CURRENTTIME = new QName("http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd", "CurrentTime");
	public static final QName TERMINATIONTIME = new QName("http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd", "TerminationTime");
	
}
