<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DCQL_2.0_Beans" xmlns="http://schemas.xmlsoap.org/wsdl/" >
	<import location="DCQL_2.0.xsd"/>
	<import location="DCQLResults_2.0.xsd"/>
</definitions>
