package gov.nih.nci.cagrid.workflow.service.globus;

import gov.nih.nci.cagrid.workflow.common.SampleService1I;
import gov.nih.nci.cagrid.workflow.service.SampleService1Impl;

import java.rmi.RemoteException;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class SampleService1ProviderImpl{
	
	SampleService1I impl;
	
	public SampleService1ProviderImpl() throws RemoteException {
		impl = new SampleService1Impl();
	}
	

	public gov.nih.nci.cagrid.workflow.stubs.InvokeResponse invoke(gov.nih.nci.cagrid.workflow.stubs.Invoke params) throws RemoteException {
		gov.nih.nci.cagrid.workflow.stubs.InvokeResponse boxedResult = new gov.nih.nci.cagrid.workflow.stubs.InvokeResponse();
		boxedResult.setResponse(impl.invoke(params.getParam()));
		return boxedResult;
	}

}
