package org.cagrid.gaards.csm.service.globus;

import org.cagrid.gaards.csm.service.CSMImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CSMImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class CSMProviderImpl{
	
	CSMImpl impl;
	
	public CSMProviderImpl() throws RemoteException {
		impl = new CSMImpl();
	}
	

    public org.cagrid.gaards.csm.stubs.GetApplicationsResponse getApplications(org.cagrid.gaards.csm.stubs.GetApplicationsRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault {
    org.cagrid.gaards.csm.stubs.GetApplicationsResponse boxedResult = new org.cagrid.gaards.csm.stubs.GetApplicationsResponse();
    boxedResult.setApplication(impl.getApplications(params.getApplicationSearchCriteria().getApplicationSearchCriteria()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.CreateApplicationResponse createApplication(org.cagrid.gaards.csm.stubs.CreateApplicationRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.CreateApplicationResponse boxedResult = new org.cagrid.gaards.csm.stubs.CreateApplicationResponse();
    boxedResult.setApplication(impl.createApplication(params.getApplication().getApplication()));
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.ModifyApplicationResponse modifyApplication(org.cagrid.gaards.csm.stubs.ModifyApplicationRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.ModifyApplicationResponse boxedResult = new org.cagrid.gaards.csm.stubs.ModifyApplicationResponse();
    impl.modifyApplication(params.getApplication().getApplication());
    return boxedResult;
  }

    public org.cagrid.gaards.csm.stubs.RemoveApplicationResponse removeApplication(org.cagrid.gaards.csm.stubs.RemoveApplicationRequest params) throws RemoteException, org.cagrid.gaards.csm.stubs.types.CSMInternalFault, org.cagrid.gaards.csm.stubs.types.AccessDeniedFault, org.cagrid.gaards.csm.stubs.types.CSMTransactionFault {
    org.cagrid.gaards.csm.stubs.RemoveApplicationResponse boxedResult = new org.cagrid.gaards.csm.stubs.RemoveApplicationResponse();
    impl.removeApplication(params.getApplicationId());
    return boxedResult;
  }

}
