package org.cagrid.gaards.dorian.service.globus;

import java.rmi.RemoteException;

import org.cagrid.gaards.dorian.service.DorianImpl;

/**
 * DO NOT EDIT: This class is autogenerated!
 * 
 * @created by Introduce Toolkit version 1.0
 */
public class DorianProviderImpl {

    DorianImpl impl;

    public DorianProviderImpl() throws RemoteException {
        impl = new DorianImpl();
    }

    public org.cagrid.gaards.dorian.stubs.RegisterWithIdPResponse registerWithIdP(org.cagrid.gaards.dorian.stubs.RegisterWithIdPRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidUserPropertyFault {
    org.cagrid.gaards.dorian.stubs.RegisterWithIdPResponse boxedResult = new org.cagrid.gaards.dorian.stubs.RegisterWithIdPResponse();
    boxedResult.setResponse(impl.registerWithIdP(params.getApplication().getApplication()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.FindLocalUsersResponse findLocalUsers(org.cagrid.gaards.dorian.stubs.FindLocalUsersRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.FindLocalUsersResponse boxedResult = new org.cagrid.gaards.dorian.stubs.FindLocalUsersResponse();
    boxedResult.setLocalUser(impl.findLocalUsers(params.getF().getLocalUserFilter()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.UpdateLocalUserResponse updateLocalUser(org.cagrid.gaards.dorian.stubs.UpdateLocalUserRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.NoSuchUserFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.UpdateLocalUserResponse boxedResult = new org.cagrid.gaards.dorian.stubs.UpdateLocalUserResponse();
    impl.updateLocalUser(params.getUser().getLocalUser());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.RemoveLocalUserResponse removeLocalUser(org.cagrid.gaards.dorian.stubs.RemoveLocalUserRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.RemoveLocalUserResponse boxedResult = new org.cagrid.gaards.dorian.stubs.RemoveLocalUserResponse();
    impl.removeLocalUser(params.getUserId());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.CreateProxyResponse createProxy(org.cagrid.gaards.dorian.stubs.CreateProxyRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidAssertionFault, org.cagrid.gaards.dorian.stubs.types.InvalidProxyFault, org.cagrid.gaards.dorian.stubs.types.UserPolicyFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.CreateProxyResponse boxedResult = new org.cagrid.gaards.dorian.stubs.CreateProxyResponse();
    boxedResult.setX509Certificate(impl.createProxy(params.getSaml().getSAMLAssertion(),params.getPublicKey().getPublicKey(),params.getLifetime().getProxyLifetime(),params.getDelegation().getDelegationPathLength()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.GetCACertificateResponse getCACertificate(org.cagrid.gaards.dorian.stubs.GetCACertificateRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault {
    org.cagrid.gaards.dorian.stubs.GetCACertificateResponse boxedResult = new org.cagrid.gaards.dorian.stubs.GetCACertificateResponse();
    boxedResult.setX509Certificate(impl.getCACertificate());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.GetTrustedIdPsResponse getTrustedIdPs(org.cagrid.gaards.dorian.stubs.GetTrustedIdPsRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.GetTrustedIdPsResponse boxedResult = new org.cagrid.gaards.dorian.stubs.GetTrustedIdPsResponse();
    boxedResult.setTrustedIdP(impl.getTrustedIdPs());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.AddTrustedIdPResponse addTrustedIdP(org.cagrid.gaards.dorian.stubs.AddTrustedIdPRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidTrustedIdPFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.AddTrustedIdPResponse boxedResult = new org.cagrid.gaards.dorian.stubs.AddTrustedIdPResponse();
    boxedResult.setTrustedIdP(impl.addTrustedIdP(params.getIdp().getTrustedIdP()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.UpdateTrustedIdPResponse updateTrustedIdP(org.cagrid.gaards.dorian.stubs.UpdateTrustedIdPRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidTrustedIdPFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.UpdateTrustedIdPResponse boxedResult = new org.cagrid.gaards.dorian.stubs.UpdateTrustedIdPResponse();
    impl.updateTrustedIdP(params.getTrustedIdP().getTrustedIdP());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.RemoveTrustedIdPResponse removeTrustedIdP(org.cagrid.gaards.dorian.stubs.RemoveTrustedIdPRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidTrustedIdPFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.RemoveTrustedIdPResponse boxedResult = new org.cagrid.gaards.dorian.stubs.RemoveTrustedIdPResponse();
    impl.removeTrustedIdP(params.getTrustedIdP().getTrustedIdP());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.FindGridUsersResponse findGridUsers(org.cagrid.gaards.dorian.stubs.FindGridUsersRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.FindGridUsersResponse boxedResult = new org.cagrid.gaards.dorian.stubs.FindGridUsersResponse();
    boxedResult.setGridUser(impl.findGridUsers(params.getFilter().getGridUserFilter()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.UpdateGridUserResponse updateGridUser(org.cagrid.gaards.dorian.stubs.UpdateGridUserRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidUserFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.UpdateGridUserResponse boxedResult = new org.cagrid.gaards.dorian.stubs.UpdateGridUserResponse();
    impl.updateGridUser(params.getUser().getGridUser());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.RemoveGridUserResponse removeGridUser(org.cagrid.gaards.dorian.stubs.RemoveGridUserRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidUserFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.RemoveGridUserResponse boxedResult = new org.cagrid.gaards.dorian.stubs.RemoveGridUserResponse();
    impl.removeGridUser(params.getUser().getGridUser());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.GetGridUserPoliciesResponse getGridUserPolicies(org.cagrid.gaards.dorian.stubs.GetGridUserPoliciesRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.GetGridUserPoliciesResponse boxedResult = new org.cagrid.gaards.dorian.stubs.GetGridUserPoliciesResponse();
    boxedResult.setGridUserPolicy(impl.getGridUserPolicies());
    return boxedResult;
  }

    public gov.nih.nci.cagrid.authentication.AuthenticateResponse authenticate(gov.nih.nci.cagrid.authentication.AuthenticateRequest params) throws RemoteException, gov.nih.nci.cagrid.authentication.stubs.types.InvalidCredentialFault, gov.nih.nci.cagrid.authentication.stubs.types.InsufficientAttributeFault, gov.nih.nci.cagrid.authentication.stubs.types.AuthenticationProviderFault {
    gov.nih.nci.cagrid.authentication.AuthenticateResponse boxedResult = new gov.nih.nci.cagrid.authentication.AuthenticateResponse();
    boxedResult.setSAMLAssertion(impl.authenticate(params.getCredential().getCredential()));
    return boxedResult;
  }

    public org.cagrid.gaards.authentication.stubs.AuthenticateUserResponse authenticateUser(org.cagrid.gaards.authentication.stubs.AuthenticateUserRequest params) throws RemoteException, org.cagrid.gaards.authentication.faults.AuthenticationProviderFault, org.cagrid.gaards.authentication.faults.CredentialNotSupportedFault, org.cagrid.gaards.authentication.faults.InsufficientAttributeFault, org.cagrid.gaards.authentication.faults.InvalidCredentialFault {
    org.cagrid.gaards.authentication.stubs.AuthenticateUserResponse boxedResult = new org.cagrid.gaards.authentication.stubs.AuthenticateUserResponse();
    boxedResult.setAssertion(impl.authenticateUser(params.getCredential().getCredential()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.AddAdminResponse addAdmin(org.cagrid.gaards.dorian.stubs.AddAdminRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.AddAdminResponse boxedResult = new org.cagrid.gaards.dorian.stubs.AddAdminResponse();
    impl.addAdmin(params.getGridIdentity());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.RemoveAdminResponse removeAdmin(org.cagrid.gaards.dorian.stubs.RemoveAdminRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.RemoveAdminResponse boxedResult = new org.cagrid.gaards.dorian.stubs.RemoveAdminResponse();
    impl.removeAdmin(params.getGridIdentity());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.GetAdminsResponse getAdmins(org.cagrid.gaards.dorian.stubs.GetAdminsRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.GetAdminsResponse boxedResult = new org.cagrid.gaards.dorian.stubs.GetAdminsResponse();
    boxedResult.setResponse(impl.getAdmins());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.RequestHostCertificateResponse requestHostCertificate(org.cagrid.gaards.dorian.stubs.RequestHostCertificateRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidHostCertificateRequestFault, org.cagrid.gaards.dorian.stubs.types.InvalidHostCertificateFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.RequestHostCertificateResponse boxedResult = new org.cagrid.gaards.dorian.stubs.RequestHostCertificateResponse();
    boxedResult.setHostCertificateRecord(impl.requestHostCertificate(params.getReq().getHostCertificateRequest()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.GetOwnedHostCertificatesResponse getOwnedHostCertificates(org.cagrid.gaards.dorian.stubs.GetOwnedHostCertificatesRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.GetOwnedHostCertificatesResponse boxedResult = new org.cagrid.gaards.dorian.stubs.GetOwnedHostCertificatesResponse();
    boxedResult.setHostCertificateRecord(impl.getOwnedHostCertificates());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.ApproveHostCertificateResponse approveHostCertificate(org.cagrid.gaards.dorian.stubs.ApproveHostCertificateRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidHostCertificateFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.ApproveHostCertificateResponse boxedResult = new org.cagrid.gaards.dorian.stubs.ApproveHostCertificateResponse();
    boxedResult.setHostCertificateRecord(impl.approveHostCertificate(params.getRecordId()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.FindHostCertificatesResponse findHostCertificates(org.cagrid.gaards.dorian.stubs.FindHostCertificatesRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.FindHostCertificatesResponse boxedResult = new org.cagrid.gaards.dorian.stubs.FindHostCertificatesResponse();
    boxedResult.setHostCertificateRecord(impl.findHostCertificates(params.getHostCertificateFilter().getHostCertificateFilter()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.UpdateHostCertificateRecordResponse updateHostCertificateRecord(org.cagrid.gaards.dorian.stubs.UpdateHostCertificateRecordRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidHostCertificateFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.UpdateHostCertificateRecordResponse boxedResult = new org.cagrid.gaards.dorian.stubs.UpdateHostCertificateRecordResponse();
    impl.updateHostCertificateRecord(params.getHostCertificateUpdate().getHostCertificateUpdate());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.RenewHostCertificateResponse renewHostCertificate(org.cagrid.gaards.dorian.stubs.RenewHostCertificateRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidHostCertificateFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.RenewHostCertificateResponse boxedResult = new org.cagrid.gaards.dorian.stubs.RenewHostCertificateResponse();
    boxedResult.setHostCertificateRecord(impl.renewHostCertificate(params.getRecordId()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.ChangeIdPUserPasswordResponse changeIdPUserPassword(org.cagrid.gaards.dorian.stubs.ChangeIdPUserPasswordRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault, org.cagrid.gaards.dorian.stubs.types.InvalidUserPropertyFault {
    org.cagrid.gaards.dorian.stubs.ChangeIdPUserPasswordResponse boxedResult = new org.cagrid.gaards.dorian.stubs.ChangeIdPUserPasswordResponse();
    impl.changeIdPUserPassword(params.getCredential().getBasicAuthCredential(),params.getNewPassword());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.DoesLocalUserExistResponse doesLocalUserExist(org.cagrid.gaards.dorian.stubs.DoesLocalUserExistRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault {
    org.cagrid.gaards.dorian.stubs.DoesLocalUserExistResponse boxedResult = new org.cagrid.gaards.dorian.stubs.DoesLocalUserExistResponse();
    boxedResult.setResponse(impl.doesLocalUserExist(params.getUserId()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.ChangeLocalUserPasswordResponse changeLocalUserPassword(org.cagrid.gaards.dorian.stubs.ChangeLocalUserPasswordRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidUserPropertyFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.ChangeLocalUserPasswordResponse boxedResult = new org.cagrid.gaards.dorian.stubs.ChangeLocalUserPasswordResponse();
    impl.changeLocalUserPassword(params.getCredential().getBasicAuthentication(),params.getNewPassword());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.UpdateUserCertificateResponse updateUserCertificate(org.cagrid.gaards.dorian.stubs.UpdateUserCertificateRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidUserCertificateFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.UpdateUserCertificateResponse boxedResult = new org.cagrid.gaards.dorian.stubs.UpdateUserCertificateResponse();
    impl.updateUserCertificate(params.getUpdate().getUserCertificateUpdate());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.RequestUserCertificateResponse requestUserCertificate(org.cagrid.gaards.dorian.stubs.RequestUserCertificateRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidAssertionFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault, org.cagrid.gaards.dorian.stubs.types.UserPolicyFault {
    org.cagrid.gaards.dorian.stubs.RequestUserCertificateResponse boxedResult = new org.cagrid.gaards.dorian.stubs.RequestUserCertificateResponse();
    boxedResult.setX509Certificate(impl.requestUserCertificate(params.getSaml().getAssertion(),params.getKey().getPublicKey(),params.getLifetime().getCertificateLifetime()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.FindUserCertificatesResponse findUserCertificates(org.cagrid.gaards.dorian.stubs.FindUserCertificatesRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidUserCertificateFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.FindUserCertificatesResponse boxedResult = new org.cagrid.gaards.dorian.stubs.FindUserCertificatesResponse();
    boxedResult.setUserCertificateRecord(impl.findUserCertificates(params.getUserCertificateFilter().getUserCertificateFilter()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.RemoveUserCertificateResponse removeUserCertificate(org.cagrid.gaards.dorian.stubs.RemoveUserCertificateRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidUserCertificateFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.RemoveUserCertificateResponse boxedResult = new org.cagrid.gaards.dorian.stubs.RemoveUserCertificateResponse();
    impl.removeUserCertificate(params.getSerialNumber());
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.PerformFederationAuditResponse performFederationAudit(org.cagrid.gaards.dorian.stubs.PerformFederationAuditRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.PerformFederationAuditResponse boxedResult = new org.cagrid.gaards.dorian.stubs.PerformFederationAuditResponse();
    boxedResult.setFederationAuditRecord(impl.performFederationAudit(params.getF().getFederationAuditFilter()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.PerformIdentityProviderAuditResponse performIdentityProviderAudit(org.cagrid.gaards.dorian.stubs.PerformIdentityProviderAuditRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.PermissionDeniedFault {
    org.cagrid.gaards.dorian.stubs.PerformIdentityProviderAuditResponse boxedResult = new org.cagrid.gaards.dorian.stubs.PerformIdentityProviderAuditResponse();
    boxedResult.setIdentityProviderAuditRecord(impl.performIdentityProviderAudit(params.getF().getIdentityProviderAuditFilter()));
    return boxedResult;
  }

    public org.cagrid.gaards.dorian.stubs.RegisterLocalUserResponse registerLocalUser(org.cagrid.gaards.dorian.stubs.RegisterLocalUserRequest params) throws RemoteException, org.cagrid.gaards.dorian.stubs.types.DorianInternalFault, org.cagrid.gaards.dorian.stubs.types.InvalidUserPropertyFault {
    org.cagrid.gaards.dorian.stubs.RegisterLocalUserResponse boxedResult = new org.cagrid.gaards.dorian.stubs.RegisterLocalUserResponse();
    boxedResult.setResponse(impl.registerLocalUser(params.getA().getApplication()));
    return boxedResult;
  }

}
