package org.cagrid.mms.service.globus;

import org.cagrid.mms.service.MetadataModelServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the MetadataModelServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class MetadataModelServiceProviderImpl{
	
	MetadataModelServiceImpl impl;
	
	public MetadataModelServiceProviderImpl() throws RemoteException {
		impl = new MetadataModelServiceImpl();
	}
	

    public org.cagrid.mms.stubs.GenerateDomainModelForProjectResponse generateDomainModelForProject(org.cagrid.mms.stubs.GenerateDomainModelForProjectRequest params) throws RemoteException, org.cagrid.mms.stubs.types.InvalidUMLProjectIndentifier {
    org.cagrid.mms.stubs.GenerateDomainModelForProjectResponse boxedResult = new org.cagrid.mms.stubs.GenerateDomainModelForProjectResponse();
    boxedResult.setDomainModel(impl.generateDomainModelForProject(params.getUmlProjectIdentifer().getUMLProjectIdentifer()));
    return boxedResult;
  }

    public org.cagrid.mms.stubs.GenerateDomainModelForPackagesResponse generateDomainModelForPackages(org.cagrid.mms.stubs.GenerateDomainModelForPackagesRequest params) throws RemoteException, org.cagrid.mms.stubs.types.InvalidUMLProjectIndentifier {
    org.cagrid.mms.stubs.GenerateDomainModelForPackagesResponse boxedResult = new org.cagrid.mms.stubs.GenerateDomainModelForPackagesResponse();
    boxedResult.setDomainModel(impl.generateDomainModelForPackages(params.getUmlProjectIdentifer().getUMLProjectIdentifer(),params.getPackageNames()));
    return boxedResult;
  }

    public org.cagrid.mms.stubs.GenerateDomainModelForClassesResponse generateDomainModelForClasses(org.cagrid.mms.stubs.GenerateDomainModelForClassesRequest params) throws RemoteException, org.cagrid.mms.stubs.types.InvalidUMLProjectIndentifier {
    org.cagrid.mms.stubs.GenerateDomainModelForClassesResponse boxedResult = new org.cagrid.mms.stubs.GenerateDomainModelForClassesResponse();
    boxedResult.setDomainModel(impl.generateDomainModelForClasses(params.getUmlProjectIdentifer().getUMLProjectIdentifer(),params.getFullyQualifiedClassNames()));
    return boxedResult;
  }

    public org.cagrid.mms.stubs.GenerateDomainModelForClassesWithExcludesResponse generateDomainModelForClassesWithExcludes(org.cagrid.mms.stubs.GenerateDomainModelForClassesWithExcludesRequest params) throws RemoteException, org.cagrid.mms.stubs.types.InvalidUMLProjectIndentifier {
    org.cagrid.mms.stubs.GenerateDomainModelForClassesWithExcludesResponse boxedResult = new org.cagrid.mms.stubs.GenerateDomainModelForClassesWithExcludesResponse();
    boxedResult.setDomainModel(impl.generateDomainModelForClassesWithExcludes(params.getUmlProjectIdentifer().getUMLProjectIdentifer(),params.getFullyQualifiedClassNames(),params.getUmlAssociationExclude().getUMLAssociationExclude()));
    return boxedResult;
  }

    public org.cagrid.mms.stubs.AnnotateServiceMetadataResponse annotateServiceMetadata(org.cagrid.mms.stubs.AnnotateServiceMetadataRequest params) throws RemoteException, org.cagrid.mms.stubs.types.InvalidUMLProjectIndentifier {
    org.cagrid.mms.stubs.AnnotateServiceMetadataResponse boxedResult = new org.cagrid.mms.stubs.AnnotateServiceMetadataResponse();
    boxedResult.setServiceMetadata(impl.annotateServiceMetadata(params.getServiceMetadata().getServiceMetadata(),params.getNamespaceToProjectMappings().getNamespaceToProjectMapping()));
    return boxedResult;
  }

    public org.cagrid.mms.stubs.GetModelSourceMetadataResponse getModelSourceMetadata(org.cagrid.mms.stubs.GetModelSourceMetadataRequest params) throws RemoteException {
    org.cagrid.mms.stubs.GetModelSourceMetadataResponse boxedResult = new org.cagrid.mms.stubs.GetModelSourceMetadataResponse();
    boxedResult.setModelSourceMetadata(impl.getModelSourceMetadata());
    return boxedResult;
  }

}
