package gov.nih.nci.cagrid.identifiers.client;

import java.net.URI;
import java.rmi.RemoteException;
import java.util.ArrayList;

import namingauthority.IdentifierValues;
import namingauthority.KeyData;
import namingauthority.KeyValues;
import org.apache.axis.client.Stub;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;
import org.globus.gsi.GlobusCredential;
import gov.nih.nci.cagrid.identifiers.common.IdentifiersNAServiceI;
import gov.nih.nci.cagrid.identifiers.common.IdentifiersNAUtil;
import gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.3
 */
public class IdentifiersNAServiceClient extends IdentifiersNAServiceClientBase implements IdentifiersNAServiceI {	

	public IdentifiersNAServiceClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public IdentifiersNAServiceClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public IdentifiersNAServiceClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public IdentifiersNAServiceClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(IdentifiersNAServiceClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  IdentifiersNAServiceClient client = new IdentifiersNAServiceClient(args[1]);
			  client.setAnonymousPrefered(true);
			  
			  // place client calls here if you want to use this main as a
			  // test....
			  KeyValues[] keyValues1 = new KeyValues[2];
			  keyValues1[0] = new KeyValues();
			  keyValues1[0].setKey("URL");
			  keyValues1[0].setKeyData(new KeyData(null,
					  new String[] { "http://www.google.com" }));

			  keyValues1[1] = new KeyValues();
			  keyValues1[1].setKey("CODE");
			  keyValues1[1].setKeyData(new KeyData(null,
					  new String[] { "end point reference 1", "end point reference 2" }));
	
			  IdentifierValues values1 = new IdentifierValues(keyValues1);
			  IdentifierValues values2 = null;

			  org.apache.axis.types.URI identifier = client.createIdentifier(values1);
			  System.out.println("Identifier: " + identifier.toString());
			  
			  //////////////////////////////////////////////////////////////////////
			  // Test identifier keys with no values are supported
			  //
			  System.out.println(client.createIdentifier(null).toString());
			  System.out.println(client.createIdentifier(new IdentifierValues()));
			  
			  IdentifierValues values = new IdentifierValues();
			  values.setKeyValues(null);
			  System.out.println(client.createIdentifier(values).toString());
			  
			  values.setKeyValues(new KeyValues[]{});
			  System.out.println(client.createIdentifier(values).toString());

			  KeyValues[] kvs = new KeyValues[] {
				new KeyValues("key1", null),
				new KeyValues("key2", new KeyData()),
				new KeyValues("key3", new KeyData(null, null)),
				new KeyValues("key4", new KeyData(null, new String[]{}))
			  };
			  values.setKeyValues(kvs);
			  System.out.println(client.createIdentifier(values));

			  // Try inserting a key with no name
			  kvs = new KeyValues[] {
					new KeyValues("", null),
					new KeyValues("key2", new KeyData())
			  };
			  values.setKeyValues(kvs);
			  System.out.println(client.createIdentifier(values));
					  
//
//			  values2 = client.resolveIdentifier(identifier);
//			  System.out.println("\n-------------------------------------\nAfter creating identifier:");
//			  printValues(values2);
//
//
//			  IdentifiersNAUtil.assertEquals(values1, values2);
			  
			  ////////////////////////////////////////
			  // Add couple of other keys
			  ////////////////////////////////////////
//			  KeyValues[] newKeyValues = new KeyValues[2];
//			  newKeyValues[0] = new KeyValues();
//			  newKeyValues[0].setKey("KEY3");
//			  newKeyValues[0].setKeyData(new KeyData(null, new String[]{"KEY3 VALUE"}));
//			  newKeyValues[1] = new KeyValues();
//			  newKeyValues[1].setKey("KEY4");
//			  newKeyValues[1].setKeyData(new KeyData(null, new String[]{"KEY4 VALUE"}));
//			  client.createKeys(identifier, new IdentifierValues(newKeyValues));
//			  values2 = client.resolveIdentifier(identifier);
//			  System.out.println("After createKeys:");
//			  System.out.println(values2.toString());
			  
			  // Delete all keys
//			  client.deleteAllKeys(identifier);
//			  IdentifierValues deleteAllKeysValues = client.resolveIdentifier(identifier);
//			  System.out.println("\n-------------------------------\nAfter deleteAllKeys:");
//			  printValues(deleteAllKeysValues);
			  
			  //Delete some keys
			  client.deleteKeys(identifier, new String[]{ "URL" });
			  IdentifierValues deleteKeysValues = client.resolveIdentifier(identifier);
			  System.out.println("\n-----------------------------------------------\nAfter deleteKeys:");
			  printValues(deleteKeysValues);
			  
			  //Replace some keys
//			  KeyValues[] replacedKeys = new KeyValues[2];
//			  replacedKeys[0] = new KeyValues();
//			  replacedKeys[0].setKey("EPR");
//			  replacedKeys[0].setKeyData(new KeyData(null, new String[] {"end point reference 3"}));
//			  
//			  replacedKeys[1] = new KeyValues();
//			  replacedKeys[1].setKey("URL");
//			  replacedKeys[1].setKeyData(new KeyData(null, new String[] {"http://www.casafiesta.com"}));
//			  
//			  client.replaceKeys(identifier, new IdentifierValues(replacedKeys));
//			  IdentifierValues replacedValues = client.resolveIdentifier(identifier);
//			  System.out.println("\n***************\nAfter replacedKeys:");
//			  printValues(replacedValues);				
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

	private static void printValues(IdentifierValues values) {
		if (values == null) {
			return;
		}
		
		for( KeyValues kv : values.getKeyValues()) {
			  System.out.println("\n***********************\nKEY: " + kv.getKey());
			  KeyData kd = kv.getKeyData();
			  if (kd != null && kd.getValue() != null) {
				  for(String value : kd.getValue()) {
					  System.out.println("\t\tVALUE: " + value);
				  }
			  }
		  }
	}
	

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

  public org.apache.axis.types.URI createIdentifier(namingauthority.IdentifierValues identifierValues) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"createIdentifier");
    gov.nih.nci.cagrid.identifiers.stubs.CreateIdentifierRequest params = new gov.nih.nci.cagrid.identifiers.stubs.CreateIdentifierRequest();
    gov.nih.nci.cagrid.identifiers.stubs.CreateIdentifierRequestIdentifierValues identifierValuesContainer = new gov.nih.nci.cagrid.identifiers.stubs.CreateIdentifierRequestIdentifierValues();
    identifierValuesContainer.setIdentifierValues(identifierValues);
    params.setIdentifierValues(identifierValuesContainer);
    gov.nih.nci.cagrid.identifiers.stubs.CreateIdentifierResponse boxedResult = portType.createIdentifier(params);
    return boxedResult.getIdentifier();
    }
  }

  public namingauthority.IdentifierValues resolveIdentifier(org.apache.axis.types.URI identifier) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"resolveIdentifier");
    gov.nih.nci.cagrid.identifiers.stubs.ResolveIdentifierRequest params = new gov.nih.nci.cagrid.identifiers.stubs.ResolveIdentifierRequest();
    gov.nih.nci.cagrid.identifiers.stubs.ResolveIdentifierRequestIdentifier identifierContainer = new gov.nih.nci.cagrid.identifiers.stubs.ResolveIdentifierRequestIdentifier();
    identifierContainer.setIdentifier(identifier);
    params.setIdentifier(identifierContainer);
    gov.nih.nci.cagrid.identifiers.stubs.ResolveIdentifierResponse boxedResult = portType.resolveIdentifier(params);
    return boxedResult.getIdentifierValues();
    }
  }

  public void deleteKeys(org.apache.axis.types.URI identifier,java.lang.String[] keyList) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"deleteKeys");
    gov.nih.nci.cagrid.identifiers.stubs.DeleteKeysRequest params = new gov.nih.nci.cagrid.identifiers.stubs.DeleteKeysRequest();
    gov.nih.nci.cagrid.identifiers.stubs.DeleteKeysRequestIdentifier identifierContainer = new gov.nih.nci.cagrid.identifiers.stubs.DeleteKeysRequestIdentifier();
    identifierContainer.setIdentifier(identifier);
    params.setIdentifier(identifierContainer);
    params.setKeyList(keyList);
    gov.nih.nci.cagrid.identifiers.stubs.DeleteKeysResponse boxedResult = portType.deleteKeys(params);
    }
  }

  public void createKeys(org.apache.axis.types.URI identifier,namingauthority.IdentifierValues identifierValues) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"createKeys");
    gov.nih.nci.cagrid.identifiers.stubs.CreateKeysRequest params = new gov.nih.nci.cagrid.identifiers.stubs.CreateKeysRequest();
    gov.nih.nci.cagrid.identifiers.stubs.CreateKeysRequestIdentifier identifierContainer = new gov.nih.nci.cagrid.identifiers.stubs.CreateKeysRequestIdentifier();
    identifierContainer.setIdentifier(identifier);
    params.setIdentifier(identifierContainer);
    gov.nih.nci.cagrid.identifiers.stubs.CreateKeysRequestIdentifierValues identifierValuesContainer = new gov.nih.nci.cagrid.identifiers.stubs.CreateKeysRequestIdentifierValues();
    identifierValuesContainer.setIdentifierValues(identifierValues);
    params.setIdentifierValues(identifierValuesContainer);
    gov.nih.nci.cagrid.identifiers.stubs.CreateKeysResponse boxedResult = portType.createKeys(params);
    }
  }

  public void replaceKeys(org.apache.axis.types.URI identifier,namingauthority.IdentifierValues identifierValues) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"replaceKeys");
    gov.nih.nci.cagrid.identifiers.stubs.ReplaceKeysRequest params = new gov.nih.nci.cagrid.identifiers.stubs.ReplaceKeysRequest();
    gov.nih.nci.cagrid.identifiers.stubs.ReplaceKeysRequestIdentifier identifierContainer = new gov.nih.nci.cagrid.identifiers.stubs.ReplaceKeysRequestIdentifier();
    identifierContainer.setIdentifier(identifier);
    params.setIdentifier(identifierContainer);
    gov.nih.nci.cagrid.identifiers.stubs.ReplaceKeysRequestIdentifierValues identifierValuesContainer = new gov.nih.nci.cagrid.identifiers.stubs.ReplaceKeysRequestIdentifierValues();
    identifierValuesContainer.setIdentifierValues(identifierValues);
    params.setIdentifierValues(identifierValuesContainer);
    gov.nih.nci.cagrid.identifiers.stubs.ReplaceKeysResponse boxedResult = portType.replaceKeys(params);
    }
  }

  public java.lang.String[] getKeys(org.apache.axis.types.URI identifier) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getKeys");
    gov.nih.nci.cagrid.identifiers.stubs.GetKeysRequest params = new gov.nih.nci.cagrid.identifiers.stubs.GetKeysRequest();
    gov.nih.nci.cagrid.identifiers.stubs.GetKeysRequestIdentifier identifierContainer = new gov.nih.nci.cagrid.identifiers.stubs.GetKeysRequestIdentifier();
    identifierContainer.setIdentifier(identifier);
    params.setIdentifier(identifierContainer);
    gov.nih.nci.cagrid.identifiers.stubs.GetKeysResponse boxedResult = portType.getKeys(params);
    return boxedResult.getResponse();
    }
  }

  public java.lang.String[] getKeyValues(org.apache.axis.types.URI identifier,java.lang.String keyName) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getKeyValues");
    gov.nih.nci.cagrid.identifiers.stubs.GetKeyValuesRequest params = new gov.nih.nci.cagrid.identifiers.stubs.GetKeyValuesRequest();
    gov.nih.nci.cagrid.identifiers.stubs.GetKeyValuesRequestIdentifier identifierContainer = new gov.nih.nci.cagrid.identifiers.stubs.GetKeyValuesRequestIdentifier();
    identifierContainer.setIdentifier(identifier);
    params.setIdentifier(identifierContainer);
    params.setKeyName(keyName);
    gov.nih.nci.cagrid.identifiers.stubs.GetKeyValuesResponse boxedResult = portType.getKeyValues(params);
    return boxedResult.getResponse();
    }
  }

}
