drop database if exists IDENTIFIERS;

create database IDENTIFIERS;

use IDENTIFIERS;

DROP TABLE IF EXISTS IDENTIFIER_VALUES;
CREATE TABLE IDENTIFIER_VALUES (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  type varchar(255) NOT NULL,
  data varchar(2048) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
