package org.cagrid.metrics.service.globus;

import org.cagrid.metrics.service.MetricsImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the MetricsImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public class MetricsProviderImpl{
	
	MetricsImpl impl;
	
	public MetricsProviderImpl() throws RemoteException {
		impl = new MetricsImpl();
	}
	

    public org.cagrid.metrics.stubs.ReportResponse report(org.cagrid.metrics.stubs.ReportRequest params) throws RemoteException {
    org.cagrid.metrics.stubs.ReportResponse boxedResult = new org.cagrid.metrics.stubs.ReportResponse();
    impl.report(params.getSubmission().getEventSubmission());
    return boxedResult;
  }

}
