package org.cagrid.gme.service.globus;

import java.rmi.RemoteException;

import org.cagrid.gme.service.GlobalModelExchangeImpl;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the GlobalModelExchangeImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class GlobalModelExchangeProviderImpl{
	
	GlobalModelExchangeImpl impl;
	
	public GlobalModelExchangeProviderImpl() throws RemoteException {
		impl = new GlobalModelExchangeImpl();
	}
	

    public org.cagrid.gme.stubs.PublishXMLSchemasResponse publishXMLSchemas(org.cagrid.gme.stubs.PublishXMLSchemasRequest params) throws RemoteException, org.cagrid.gme.stubs.types.InvalidSchemaSubmissionFault {
    org.cagrid.gme.stubs.PublishXMLSchemasResponse boxedResult = new org.cagrid.gme.stubs.PublishXMLSchemasResponse();
    impl.publishXMLSchemas(params.getSchemas().getXMLSchema());
    return boxedResult;
  }

    public org.cagrid.gme.stubs.GetXMLSchemaResponse getXMLSchema(org.cagrid.gme.stubs.GetXMLSchemaRequest params) throws RemoteException, org.cagrid.gme.stubs.types.NoSuchNamespaceExistsFault {
    org.cagrid.gme.stubs.GetXMLSchemaResponse boxedResult = new org.cagrid.gme.stubs.GetXMLSchemaResponse();
    boxedResult.setXMLSchema(impl.getXMLSchema(params.getTargetNamespace().getXMLSchemaNamespace()));
    return boxedResult;
  }

    public org.cagrid.gme.stubs.GetXMLSchemaNamespacesResponse getXMLSchemaNamespaces(org.cagrid.gme.stubs.GetXMLSchemaNamespacesRequest params) throws RemoteException {
    org.cagrid.gme.stubs.GetXMLSchemaNamespacesResponse boxedResult = new org.cagrid.gme.stubs.GetXMLSchemaNamespacesResponse();
    boxedResult.setXMLSchemaNamespace(impl.getXMLSchemaNamespaces());
    return boxedResult;
  }

    public org.cagrid.gme.stubs.GetXMLSchemaAndDependenciesResponse getXMLSchemaAndDependencies(org.cagrid.gme.stubs.GetXMLSchemaAndDependenciesRequest params) throws RemoteException, org.cagrid.gme.stubs.types.NoSuchNamespaceExistsFault {
    org.cagrid.gme.stubs.GetXMLSchemaAndDependenciesResponse boxedResult = new org.cagrid.gme.stubs.GetXMLSchemaAndDependenciesResponse();
    boxedResult.setXMLSchemaBundle(impl.getXMLSchemaAndDependencies(params.getTargetNamespace().getXMLSchemaNamespace()));
    return boxedResult;
  }

    public org.cagrid.gme.stubs.DeleteXMLSchemasResponse deleteXMLSchemas(org.cagrid.gme.stubs.DeleteXMLSchemasRequest params) throws RemoteException, org.cagrid.gme.stubs.types.NoSuchNamespaceExistsFault, org.cagrid.gme.stubs.types.UnableToDeleteSchemaFault {
    org.cagrid.gme.stubs.DeleteXMLSchemasResponse boxedResult = new org.cagrid.gme.stubs.DeleteXMLSchemasResponse();
    impl.deleteXMLSchemas(params.getTargetNamespaces().getXMLSchemaNamespace());
    return boxedResult;
  }

    public org.cagrid.gme.stubs.GetImportedXMLSchemaNamespacesResponse getImportedXMLSchemaNamespaces(org.cagrid.gme.stubs.GetImportedXMLSchemaNamespacesRequest params) throws RemoteException, org.cagrid.gme.stubs.types.NoSuchNamespaceExistsFault {
    org.cagrid.gme.stubs.GetImportedXMLSchemaNamespacesResponse boxedResult = new org.cagrid.gme.stubs.GetImportedXMLSchemaNamespacesResponse();
    boxedResult.setXMLSchemaNamespace(impl.getImportedXMLSchemaNamespaces(params.getTargetNamespace().getXMLSchemaNamespace()));
    return boxedResult;
  }

    public org.cagrid.gme.stubs.GetImportingXMLSchemaNamespacesResponse getImportingXMLSchemaNamespaces(org.cagrid.gme.stubs.GetImportingXMLSchemaNamespacesRequest params) throws RemoteException, org.cagrid.gme.stubs.types.NoSuchNamespaceExistsFault {
    org.cagrid.gme.stubs.GetImportingXMLSchemaNamespacesResponse boxedResult = new org.cagrid.gme.stubs.GetImportingXMLSchemaNamespacesResponse();
    boxedResult.setXMLSchemaNamespace(impl.getImportingXMLSchemaNamespaces(params.getTargetNamespace().getXMLSchemaNamespace()));
    return boxedResult;
  }

}
