package gov.nih.nci.cagrid.workflow.samples.secure.common;

import java.rmi.RemoteException;

/** 
 *   This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface SecureSampleI {







     public java.lang.String invoke(java.lang.String string) throws RemoteException ;

}

