package gov.nih.nci.cagrid.workflow.samples.secure.service.globus;

/** 
 *  DO NOT EDIT:  This class is autogenerated!
 * 
 *  @created by Introduce Toolkit version 1.0
 * 
 */
public class ServiceConfiguration {
	

	
}
