/**
*============================================================================
*  Copyright The Ohio State University Research Foundation, The University of Chicago - 
*	Argonne National Laboratory, Emory University, SemanticBits LLC, and 
*	Ekagra Software Technologies Ltd.
*
*  Distributed under the OSI-approved BSD 3-Clause License.
*  See http://ncip.github.com/cagrid-core/LICENSE.txt for details.
*============================================================================
**/
package gov.nih.nci.cagrid.enumeration.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface CaGridEnumerationConstantsBase {
	public static final String SERVICE_NS = "http://gov.nih.nci.cagrid.enumeration/CaGridEnumeration";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "CaGridEnumerationKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "CaGridEnumerationResourceProperties");
	
}
