package gov.nih.nci.cagrid.gts.common;

import gov.nih.nci.cagrid.gts.stubs.types.CertificateValidationFault;
import gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault;
import gov.nih.nci.cagrid.gts.stubs.types.IllegalAuthorityFault;
import gov.nih.nci.cagrid.gts.stubs.types.IllegalPermissionFault;
import gov.nih.nci.cagrid.gts.stubs.types.IllegalTrustLevelFault;
import gov.nih.nci.cagrid.gts.stubs.types.IllegalTrustedAuthorityFault;
import gov.nih.nci.cagrid.gts.stubs.types.InvalidAuthorityFault;
import gov.nih.nci.cagrid.gts.stubs.types.InvalidPermissionFault;
import gov.nih.nci.cagrid.gts.stubs.types.InvalidTrustLevelFault;
import gov.nih.nci.cagrid.gts.stubs.types.InvalidTrustedAuthorityFault;
import gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault;

import java.rmi.RemoteException;

/**
 * Grid Trust Service (GTS)
 *
 * This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 */
public interface GTSI {

	public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata()
		throws RemoteException;

  /**
   * Publish a Certificate Authority to the trust fabric.
   *
   * @param ta
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws IllegalTrustedAuthorityFault
   *	Illegal certificate authority specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public gov.nih.nci.cagrid.gts.bean.TrustedAuthority addTrustedAuthority(gov.nih.nci.cagrid.gts.bean.TrustedAuthority ta) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.IllegalTrustedAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Discover a list of trusted authorities that meets a specified trust criteria.
   *
   * @param filter
   */
  public gov.nih.nci.cagrid.gts.bean.TrustedAuthority[] findTrustedAuthorities(gov.nih.nci.cagrid.gts.bean.TrustedAuthorityFilter filter) throws RemoteException ;

  /**
   * Remove a certficate authority from the trust fabric.
   *
   * @param trustedAuthorityName
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws InvalidTrustedAuthorityFault
   *	Invalid certificate authority specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void removeTrustedAuthority(java.lang.String trustedAuthorityName) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.InvalidTrustedAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Grant a permission to a user or service.
   *
   * @param permission
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws IllegalPermissionFault
   *	Illegal permission specified by the client.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void addPermission(gov.nih.nci.cagrid.gts.bean.Permission permission) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.IllegalPermissionFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * List the permissions granted on the GTS.
   *
   * @param filter
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public gov.nih.nci.cagrid.gts.bean.Permission[] findPermissions(gov.nih.nci.cagrid.gts.bean.PermissionFilter filter) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Revoke a permission that was granted to a user or service.
   *
   * @param permission
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws InvalidPermissionFault
   *	Invalid permission specified by the client.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void revokePermission(gov.nih.nci.cagrid.gts.bean.Permission permission) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.InvalidPermissionFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Update a certificate authority's information.
   *
   * @param ta
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws IllegalTrustedAuthorityFault
   *	Illegal certificate authority specified.
   * @throws InvalidTrustedAuthorityFault
   *	Invalid certificate authority specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void updateTrustedAuthority(gov.nih.nci.cagrid.gts.bean.TrustedAuthority ta) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.IllegalTrustedAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.InvalidTrustedAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Create a trust level.
   *
   * @param trustLevel
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws IllegalTrustLevelFault
   *	Illegal trust level specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void addTrustLevel(gov.nih.nci.cagrid.gts.bean.TrustLevel trustLevel) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.IllegalTrustLevelFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Update a trust level's information.
   *
   * @param trustLevel
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws InvalidTrustLevelFault
   *	Invalid trust level specified.
   * @throws IllegalTrustLevelFault
   *	Illegal trust level specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void updateTrustLevel(gov.nih.nci.cagrid.gts.bean.TrustLevel trustLevel) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.InvalidTrustLevelFault, gov.nih.nci.cagrid.gts.stubs.types.IllegalTrustLevelFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * List the trust level define for the GTS.
   *
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   */
  public gov.nih.nci.cagrid.gts.bean.TrustLevel[] getTrustLevels() throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault ;

  /**
   * Remove a trust level from a GTS.
   *
   * @param trustLevelName
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws InvalidTrustLevelFault
   *	Invalid trust level specified.
   * @throws IllegalTrustLevelFault
   *	Illegal trust level specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void removeTrustLevel(java.lang.String trustLevelName) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.InvalidTrustLevelFault, gov.nih.nci.cagrid.gts.stubs.types.IllegalTrustLevelFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Add an Authority GTS to a GTS.
   *
   * @param authorityGTS
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws IllegalAuthorityFault
   *	Illegal authority GTS specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void addAuthority(gov.nih.nci.cagrid.gts.bean.AuthorityGTS authorityGTS) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.IllegalAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Update the information for an Authority GTS.
   *
   * @param authorityGTS
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws IllegalAuthorityFault
   *	Illegal authority GTS specified.
   * @throws InvalidAuthorityFault
   *	Invalid authority GTS specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void updateAuthority(gov.nih.nci.cagrid.gts.bean.AuthorityGTS authorityGTS) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.IllegalAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.InvalidAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Update the priorities of a GTS's authorities.
   *
   * @param authorityPriorityUpdate
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws IllegalAuthorityFault
   *	Illegal authority GTS specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void updateAuthorityPriorities(gov.nih.nci.cagrid.gts.bean.AuthorityPriorityUpdate authorityPriorityUpdate) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.IllegalAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * List the GTS's authorities.
   *
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   */
  public gov.nih.nci.cagrid.gts.bean.AuthorityGTS[] getAuthorities() throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault ;

  /**
   * Remove one of a GTS's authorities.
   *
   * @param serviceURI
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws InvalidAuthorityFault
   *	Invalid authority GTS specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void removeAuthority(java.lang.String serviceURI) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.InvalidAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Publish an updated CRL for a certificate authority.
   *
   * @param trustedAuthorityName
   * @param crl
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws IllegalTrustedAuthorityFault
   *	Illegal Certificate Authority Specified.
   * @throws InvalidTrustedAuthorityFault
   *	Invalid Certificate Authority Specified.
   * @throws PermissionDeniedFault
   *	Client does not have permission to perform the operation.
   */
  public void updateCRL(java.lang.String trustedAuthorityName,gov.nih.nci.cagrid.gts.bean.X509CRL crl) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.IllegalTrustedAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.InvalidTrustedAuthorityFault, gov.nih.nci.cagrid.gts.stubs.types.PermissionDeniedFault ;

  /**
   * Validate a certificate against the trust fabric. 
   *
   * @param chain
   * @param filter
   * @throws GTSInternalFault
   *	An unexpected internal GTS error.
   * @throws CertificateValidationFault
   *	The certificate specified is invalid.
   */
  public boolean validate(gov.nih.nci.cagrid.gts.bean.X509Certificate[] chain,gov.nih.nci.cagrid.gts.bean.TrustedAuthorityFilter filter) throws RemoteException, gov.nih.nci.cagrid.gts.stubs.types.GTSInternalFault, gov.nih.nci.cagrid.gts.stubs.types.CertificateValidationFault ;

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

}
