package gov.nih.nci.cagrid.bdt.common;

import gov.nih.nci.cagrid.enumeration.stubs.response.EnumerationResponseContainer;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public interface BulkDataHandlerI {

  public EnumerationResponseContainer createEnumeration() throws RemoteException ;

  public org.globus.transfer.AnyXmlType get(org.globus.transfer.EmptyType params) throws RemoteException ;

  public org.apache.axis.types.URI[] getGridFTPURLs() throws RemoteException ;

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException ;

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException ;

}

