package org.cagrid.gme.service;

import gov.nih.nci.cagrid.introduce.servicetools.ServiceConfiguration;

import org.globus.wsrf.config.ContainerConfig;
import java.io.File;
import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 * 
 * This class holds all service properties which were defined for the service to have
 * access to.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class GlobalModelExchangeConfiguration implements ServiceConfiguration {

	public static GlobalModelExchangeConfiguration  configuration = null;
    public String etcDirectoryPath;
    	
	public static GlobalModelExchangeConfiguration getConfiguration() throws Exception {
		if (GlobalModelExchangeConfiguration.configuration != null) {
			return GlobalModelExchangeConfiguration.configuration;
		}
		MessageContext ctx = MessageContext.getCurrentContext();

		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/serviceconfiguration";
		try {
			javax.naming.Context initialContext = new InitialContext();
			GlobalModelExchangeConfiguration.configuration = (GlobalModelExchangeConfiguration) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate service configuration.", e);
		}

		return GlobalModelExchangeConfiguration.configuration;
	}
	

	
	private String gmeConfigurationFile;
	
	private String gmePropertiesFile;
	
	
    public String getEtcDirectoryPath() {
		return ContainerConfig.getBaseDirectory() + File.separator + etcDirectoryPath;
	}
	
	public void setEtcDirectoryPath(String etcDirectoryPath) {
		this.etcDirectoryPath = etcDirectoryPath;
	}


	
	public String getGmeConfigurationFile() {
		return ContainerConfig.getBaseDirectory() + File.separator + gmeConfigurationFile;
	}
	
	
	public void setGmeConfigurationFile(String gmeConfigurationFile) {
		this.gmeConfigurationFile = gmeConfigurationFile;
	}

	
	public String getGmePropertiesFile() {
		return ContainerConfig.getBaseDirectory() + File.separator + gmePropertiesFile;
	}
	
	
	public void setGmePropertiesFile(String gmePropertiesFile) {
		this.gmePropertiesFile = gmePropertiesFile;
	}

	
}
