package gov.nih.nci.cagrid.workflow.client;


import java.net.URL;
import java.io.InputStream;
import java.rmi.RemoteException;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.Address;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.utils.ClassUtils;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.cagrid.workflow.stubs.SampleService2PortType;
import gov.nih.nci.cagrid.workflow.stubs.service.SampleService2ServiceAddressingLocator;
import gov.nih.nci.cagrid.workflow.common.SampleService2I;


/**
 * This class is autogenerated, DO NOT EDIT.
 * 
 * @created by Introduce Toolkit version 1.0
 */
public class SampleService2Client implements SampleService2I {	
	private GlobusCredential proxy;
	private String url;
	
	static{
		org.globus.axis.util.Util.registerTransport();
	}
	
	public SampleService2Client(String url) {
		this(url,null);	
	}

	public SampleService2Client(String url, GlobusCredential proxy) {
	   	this.proxy = proxy;
	   	this.url = url;	
	}

	private SampleService2PortType getPortType() throws RemoteException {

		SampleService2ServiceAddressingLocator locator = new SampleService2ServiceAddressingLocator();
		// attempt to load our context sensitive wsdd file
		InputStream resourceAsStream = ClassUtils.getResourceAsStream(getClass(), "client-config.wsdd");
		if (resourceAsStream != null) {
			// we found it, so tell axis to configure an engine to use it
			EngineConfiguration engineConfig = new FileProvider(resourceAsStream);
			// set the engine of the locator
			locator.setEngine(new AxisClient(engineConfig));
		}
		SampleService2PortType port = null;
		EndpointReferenceType endpoint = new EndpointReferenceType();
		try {
			endpoint.setAddress(new Address(url));
			port = locator.getSampleService2PortTypePort(endpoint);
		} catch (Exception e) {
			throw new RemoteException("Unable to configured porttype:" + e.getMessage(), e);
		}

		return port;
	}
	
	public static void usage(){
		System.out.println(SampleService2Client.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  SampleService2Client client = new SampleService2Client(args[1]);
			  String returnString = client.invoke("Hello");
			  System.out.println("Got this : "+ returnString);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	




	     public java.lang.String invoke(java.lang.String param) throws RemoteException {
               SampleService2PortType port = this.getPortType();
               org.apache.axis.client.Stub stub = (org.apache.axis.client.Stub) port;

               gov.nih.nci.cagrid.workflow.stubs.Invoke params = new gov.nih.nci.cagrid.workflow.stubs.Invoke();
               params.setParam(param);
               gov.nih.nci.cagrid.workflow.stubs.InvokeResponse boxedResult = port.invoke(params);
               return boxedResult.getResponse();

	}


}
