package gov.nih.nci.cagrid.workflow.factory.service;

import gov.nih.nci.cagrid.introduce.servicetools.ServiceConfiguration;

import org.globus.wsrf.config.ContainerConfig;
import java.io.File;
import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 * 
 * This class holds all service properties which were defined for the service to have
 * access to.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class TavernaWorkflowServiceConfiguration implements ServiceConfiguration {

	public static TavernaWorkflowServiceConfiguration  configuration = null;
    public String etcDirectoryPath;
    	
	public static TavernaWorkflowServiceConfiguration getConfiguration() throws Exception {
		if (TavernaWorkflowServiceConfiguration.configuration != null) {
			return TavernaWorkflowServiceConfiguration.configuration;
		}
		MessageContext ctx = MessageContext.getCurrentContext();

		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/serviceconfiguration";
		try {
			javax.naming.Context initialContext = new InitialContext();
			TavernaWorkflowServiceConfiguration.configuration = (TavernaWorkflowServiceConfiguration) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate service configuration.", e);
		}

		return TavernaWorkflowServiceConfiguration.configuration;
	}
	

	
	private String baseRepositoryDir;
	
	private String tavernaDir;
	
	
    public String getEtcDirectoryPath() {
		return ContainerConfig.getBaseDirectory() + File.separator + etcDirectoryPath;
	}
	
	public void setEtcDirectoryPath(String etcDirectoryPath) {
		this.etcDirectoryPath = etcDirectoryPath;
	}


	
	public String getBaseRepositoryDir() {
		return baseRepositoryDir;
	}
	
	
	public void setBaseRepositoryDir(String baseRepositoryDir) {
		this.baseRepositoryDir = baseRepositoryDir;
	}

	
	public String getTavernaDir() {
		return tavernaDir;
	}
	
	
	public void setTavernaDir(String tavernaDir) {
		this.tavernaDir = tavernaDir;
	}

	
}
