package gov.nih.nci.cagrid.syncgts.service;

import gov.nih.nci.cagrid.introduce.servicetools.ServiceConfiguration;

import org.globus.wsrf.config.ContainerConfig;
import java.io.File;
import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 * 
 * This class holds all service properties which were defined for the service to have
 * access to.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class SyncGTSConfiguration implements ServiceConfiguration {

	public static SyncGTSConfiguration  configuration = null;
    public String etcDirectoryPath;
    	
	public static SyncGTSConfiguration getConfiguration() throws Exception {
		if (SyncGTSConfiguration.configuration != null) {
			return SyncGTSConfiguration.configuration;
		}
		MessageContext ctx = MessageContext.getCurrentContext();

		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/serviceconfiguration";
		try {
			javax.naming.Context initialContext = new InitialContext();
			SyncGTSConfiguration.configuration = (SyncGTSConfiguration) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate service configuration.", e);
		}

		return SyncGTSConfiguration.configuration;
	}
	

	
	private String performFirstSync;
	
	
    public String getEtcDirectoryPath() {
		return ContainerConfig.getBaseDirectory() + File.separator + etcDirectoryPath;
	}
	
	public void setEtcDirectoryPath(String etcDirectoryPath) {
		this.etcDirectoryPath = etcDirectoryPath;
	}


	
	public String getPerformFirstSync() {
		return performFirstSync;
	}
	
	
	public void setPerformFirstSync(String performFirstSync) {
		this.performFirstSync = performFirstSync;
	}

	
}
