package gov.nih.nci.cagrid.fqp.resultsretrieval.service.globus.resource;

import gov.nih.nci.cagrid.fqp.processor.FQPProcessingStatusListener;
import gov.nih.nci.cagrid.fqp.processor.exceptions.FederatedQueryProcessingException;

import org.cagrid.data.dcql.results.DCQLQueryResultsCollection;

/**
 * Adds methods to the standard FQPProcessingStatusListener
 * to return results when the query is complete and
 * indicate failure conditions
 * 
 * @author ervin
 */
public interface AsynchronousFQPProcessingStatusListener extends FQPProcessingStatusListener {

    
    /**
     * Indicates that DCQL 2 Query Results have been completely generated by the
     * query execution process
     * @param results
     */
    public void queryResultsGenerated(DCQLQueryResultsCollection results);
    
    
    /**
     * Indicates that a fatal query processing exception has occured
     * @param ex
     */
    public void queryProcessingException(FederatedQueryProcessingException ex);
}
