package org.cagrid.mms.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface MetadataModelServiceConstantsBase {
	public static final String SERVICE_NS = "http://mms.cagrid.org/MetadataModelService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "MetadataModelServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "MetadataModelServiceResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	public static final QName MODELSOURCEMETADATA = new QName("gme://caGrid.caBIG/1.0/org.cagrid.mms.domain", "ModelSourceMetadata");
	
}
